
services:

  tp-gateway:
    build:
      context: ./tp-gateway
      dockerfile: Dockerfile
    container_name: tp-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      NACOS_SERVER_ADDR: 192.168.184.130:8850
    networks:
      - tp-net

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - tp-gateway
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.184.130:3306/tp-user?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      NACOS_SERVER_ADDR: 192.168.184.130:8850
      RABBITMQ_HOST: 192.168.184.130
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: tp
      RABBITMQ_PASSWORD: 123
    networks:
      - tp-net

  itinerary-service:
    build:
      context: ./itinerary-service
      dockerfile: Dockerfile
    container_name: itinerary-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.184.130:3306/tp-itineraries?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      NACOS_SERVER_ADDR: 192.168.184.130:8850
      RABBITMQ_HOST: 192.168.184.130
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: tp
      RABBITMQ_PASSWORD: 123
    networks:
      - tp-net

  destination-service:
    build:
      context: ./destination-service
      dockerfile: Dockerfile
    container_name: destination-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - itinerary-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.184.130:3306/tp-destinations?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      NACOS_SERVER_ADDR: 192.168.184.130:8850
      RABBITMQ_HOST: 192.168.184.130
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: tp
      RABBITMQ_PASSWORD: 123
    networks:
      - tp-net

networks:
  tp-net:
    external: true
