server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.184.130:8850
    gateway:

      routes:
        - id: user # 路由规则id，自定义，唯一
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: itinerary
          uri: lb://itinerary-service
          predicates:
            - Path=/itinerary/**
          filters:
            - AddRequestHeader=key, value
        - id: destination
          uri: lb://destination-service
          predicates:
            - Path=/destination/**
          filters:
            - AddRequestHeader=key, value
gateway:
  ignoreUrls:
    - /user/**
knife4j:
  gateway:
    enabled: true
    strategy: manual
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - gateway-service
    routes:
      - name: user-service
        service-name: user-service
        context-path: /
        url: /user-service/v3/api-docs?group=user-service
        order: 1

      - name: itinerary-service
        service-name: itinerary-service
        context-path: /
        url: /itinerary-service/v3/api-docs?group=order-service
        order: 2

      - name: destination-service
        service-name: destination-service
        context-path: /
        url: /destination-service/v3/api-docs?group=finance-service
        order: 3
