server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.184.130:8850
    gateway:

      routes:
        - id: user # 路由规则id，自定义，唯一
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: itinerary
          uri: lb://itinerary-service
          predicates:
            - Path=/itinerary/**
          filters:
            - AddRequestHeader=key, value
        - id: destination
          uri: lb://destination-service
          predicates:
            - Path=/destination/**
          filters:
            - AddRequestHeader=key, value
gateway:
  ignoreUrls:
    - /user/register
