server:
  port: 8082
spring:
  application:
    name: itinerary-service
  cloud:
    nacos:
      server-addr: 192.168.184.130:8850 # nacos地址
  datasource:
    url: jdbc:mysql://192.168.184.130:3306/tp-itineraries?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"